### PR TITLE
Code cleaned

### PR DESCRIPTION
**Pull request by SardorSohinazarov**

### CODE REVIEW

**Review by Tohirjon-Odilov — APPROVED** [review]
Qoyil lekin

**Comment by QosimovIbrohim** [comment]
All right

**Review by Tohirjon-Odilov — APPROVED** [review]
Lekin malades

**Comment by QosimovIbrohim** [comment]
Salom akalar

**Review by Tohirjon-Odilov — CHANGES_REQUESTED** [review]
nimaga unaqa bo'lyaptikan

**Review by QosimovIbrohim — APPROVED** [review]
qwer

**Comment by QosimovIbrohim** [comment]
Exx attang

**Pull request merged**
